environment               = "stg"
location                  = "eastus"
resource_group_name       = "rg-sample-stg"
storage_account_name      = "stdbwsamplestg"
key_vault_name            = "kv-sample-stg"
ai_foundry_name         = "aif-sample-stg"
ai_foundry_project_name = "proj-sample-stg"
