environment               = "dev"
location                  = "eastus"
resource_group_name       = "rg-sample-dev"
storage_account_name      = "stdbwsampledev"
key_vault_name            = "kv-sample-dev"
ai_foundry_name         = "aif-sample-dev"
ai_foundry_project_name = "proj-sample-dev"
