environment               = "prd"
location                  = "eastus"
resource_group_name       = "rg-sample-prd"
databricks_workspace_name = "dbw-sample-prd"
storage_account_name      = "stdbwsampleprd"
key_vault_name            = "kv-sample-prd"
ai_foundry_name           = "aif-sample-prd"
