environment               = "prd"
location                  = "eastus"
resource_group_name       = "rg-sample-prd"
storage_account_name      = "stdbwsampleprd"
key_vault_name            = "kv-sample-prd"
ai_foundry_name         = "aif-sample-prd"
ai_foundry_project_name = "proj-sample-prd"
